# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf47e33a36edcbc76ca54622f17bd9c6554523566fdbcab3f2878fe5ab43a258984ecacea0953449dcb08f3bc283ad82c84416b227fd470f360cdd9061183454

test:
  secret_key_base: 44bb3d7e877d94650ca6596ab2b88ec0a3566f2b8b4a3847b02cdf5d60a6fedde59310d1b5dff26a60bf0031800c4977be73915828f8e7b591ce213c14f16d3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
